name: pharmacyalloc
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - networkx>=2.6.0
  - tqdm>=4.62.0
  - pip
  - pip:
    - torch>=1.9.0
    - jax>=0.3.0
    - jaxlib>=0.3.0
    - numpyro>=0.8.0
    - pyro-ppl>=1.8.0
    - pybobyqa>=1.0.0 